[package]
name = "onlyerror"
description = "Obsessively tiny error derive macro"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2021"
keywords = ["error", "derive", "error-handling"]
categories = ["no-std", "rust-patterns"]
license = "MIT"

[features]
default = ["std"]
std = []

[lib]
proc-macro = true

[dependencies]
myn = { git = "https://github.com/parasyte/myn.git", rev = "c86196dc061a2bea10363c9ed3fb7091a70e3984" }

[dev-dependencies]
error-iter = "0.4"
